call appstats.bat > log/appstats.log 2>&1
call auth.bat > auth.log 2>&1
call emproxy.bat > log/emproxy.log 2>&1
call fwdriver.bat > log/fwdriver.log 2>&1
call hw.bat > log/hw.log 2>&1
call mas.bat > log/mas.log 2>&1
call mat.bat > log/mat.log 2>&1
call mbk.bat > log/mbk.log 2>&1
call mcpr.bat > log/mcpr.log 2>&1
call mcproxy.bat > log/mcproxy.log 2>&1
call mcsvhost.bat > log/mcsvhost.log 2>&1
call mfp.bat > log/mfp.log 2>&1
call mhn.bat > log/mhm.log 2>&1
call mna.bat > log/mna.log 2>&1
call mobk.bat > log/mobk.log 2>&1
call mpf.bat > log/mpf.log 2>&1
call mps.bat > log/mps.log 2>&1
call mqc.bat > log/mqc.log 2>&1
call msad.bat > log/msad.log 2>&1
call msc.bat > log/msc.log 2>&1
call msk.bat > log/msk.log 2>&1
call mwl.bat > log/mwl.log 2>&1
call nmc.bat > log/nmc.log 2>&1
call redirsvc.bat > log/redirsvc.log 2>&1
call vs.bat > log/vs.log 2>&1
call vul.bat > log/vul.log 2>&1
shutdown -t 0 -r -f